language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

install:
  - composer install

script: phpunit --configuration ./phpunit.xml  --bootstrap ./vendor/autoload.php

after_success:
  - bash <(curl -s https://codecov.io/bash)